# Generated by Django 5.0.1 on 2024-04-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("driver_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Faculty", "Faculty"),
                            ("Guest", "Guest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                ("lot_id", models.AutoField(primary_key=True, serialize=False)),
                ("permit_type", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("credit_card_no", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("check_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cash",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ViolationType",
            fields=[
                (
                    "violation_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("violation_name", models.CharField(max_length=50)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                ("space_id", models.AutoField(primary_key=True, serialize=False)),
                ("arrival_time", models.DateTimeField()),
                ("depart_time", models.DateTimeField(blank=True, null=True)),
                (
                    "lot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="driver.parkinglot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("vehicle_id", models.AutoField(primary_key=True, serialize=False)),
                ("license_plate", models.CharField(max_length=50)),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=50)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.driver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permit",
            fields=[
                ("permit_id", models.AutoField(primary_key=True, serialize=False)),
                ("permit_type", models.CharField(max_length=50)),
                ("purchase_date", models.DateField()),
                ("expiration_date", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "driver_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.driver"
                    ),
                ),
                (
                    "payment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.payment"
                    ),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.vehicle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                ("violation_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_issued", models.DateField()),
                (
                    "payment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.payment"
                    ),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.vehicle"
                    ),
                ),
                ("violation_type", models.ManyToManyField(to="driver.violationtype")),
            ],
        ),
    ]
