# Generated by Django 5.0.1 on 2024-04-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0002_alter_permit_payment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permit",
            name="permit_type",
        ),
        migrations.AddField(
            model_name="permit",
            name="types",
            field=models.CharField(
                choices=[
                    ("upermit", "UPermit"),
                    ("cupermit", "CUPermit"),
                    ("daypermit", "DayPermit"),
                ],
                default=0,
                max_length=50,
            ),
        ),
    ]
