# Generated by Django 5.0.1 on 2024-04-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0004_alter_permit_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="types",
            field=models.CharField(
                choices=[
                    ("upermit", "UPermit"),
                    ("cupermit", "CUPermit"),
                    ("apermit", "APermit"),
                    ("daypermit", "DayPermit"),
                ],
                max_length=50,
            ),
        ),
    ]
