# Generated by Django 5.0.1 on 2024-04-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0005_alter_permit_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="violation",
            name="violation_type",
        ),
        migrations.AddField(
            model_name="violation",
            name="violation_types",
            field=models.CharField(
                choices=[
                    ("nopermit", "No Permit For Lot"),
                    ("expiredpermit", "Expired Permit"),
                    ("overnight", "Overnight Parking"),
                ],
                default="nopermit",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="ViolationType",
        ),
    ]
