# Generated by Django 5.0.1 on 2024-04-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0006_remove_violation_violation_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspace",
            name="lot_id",
        ),
        migrations.DeleteModel(
            name="ParkingLot",
        ),
        migrations.DeleteModel(
            name="ParkingSpace",
        ),
    ]
