# Generated by Django 5.0.1 on 2024-04-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0007_remove_parkingspace_lot_id_delete_parkinglot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="violation",
            name="status",
            field=models.CharField(
                choices=[("Settled", "Settled"), ("Outstanding", "Outstanding")],
                default="Outstanding",
                max_length=20,
            ),
        ),
    ]
