# Generated by Django 5.0.1 on 2024-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0008_violation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="violation",
            name="fine_amount",
            field=models.CharField(default="100.00", max_length=20),
        ),
    ]
