# Generated by Django 5.0.1 on 2024-04-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0009_violation_fine_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="permit",
            name="status",
            field=models.CharField(
                choices=[("Payed", "Payed"), ("Not Payed", "Not Payed")],
                default="Not Payed",
                max_length=20,
            ),
        ),
    ]
