# Generated by Django 5.0.1 on 2024-04-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0010_permit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="permit",
            name="amount_due",
            field=models.CharField(default="100.00", max_length=20),
        ),
    ]
