# Generated by Django 5.0.1 on 2024-04-14 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0011_permit_amount_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="permit",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 14, 15, 25, 18, 216172, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
