# Generated by Django 5.0.1 on 2024-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0012_alter_permit_cost_alter_permit_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="expiration_date",
            field=models.CharField(default="04/30/2025", max_length=20),
        ),
    ]
